# Generated by Django 4.0.2 on 2022-03-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0002_datavideostores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/Tours')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Malumotlar',
            },
        ),
    ]
