# Generated by Django 4.0.2 on 2022-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0004_alter_toursdata_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/employes')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('hobby', models.TextField()),
                ('facebook', models.URLField(max_length=1024)),
                ('instagram', models.URLField(max_length=1024)),
                ('linkedin', models.URLField(max_length=1024)),
                ('github', models.URLField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Ishchilar',
            },
        ),
    ]
