# Generated by Django 4.0.2 on 2022-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0005_employes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('context', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('poll', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
