# Generated by Django 4.0.2 on 2022-03-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0006_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCatagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Ovqatlar katagoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/foods')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('isShow', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapi.foodcatagories')),
            ],
            options={
                'verbose_name_plural': 'Ovqatlar',
            },
        ),
    ]
