# Generated by Django 4.0.2 on 2022-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0007_foodcatagories_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=128)),
                ('hobby', models.TextField()),
                ('company', models.CharField(max_length=128)),
                ('exprience', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Devolopers',
            },
        ),
        migrations.AlterField(
            model_name='foods',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='searchapi.foodcatagories'),
        ),
    ]
