# Generated by Django 4.0 on 2022-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0009_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Telefon narxi')),
                ('image', models.ImageField(upload_to='media/phone', verbose_name='Rasm')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Soni')),
            ],
            options={
                'verbose_name_plural': 'Telfonlar',
            },
        ),
    ]
